const FOOD_DATABASE = [
  // ===== חלבונים (Proteins) =====
  { id: 1, name: "חזה עוף", category: "חלבונים", calories: 165, protein: 31, carbs: 0, fat: 3.6, fiber: 0, servingSize: 150, servingDescription: "חזה אחד" },
  { id: 2, name: "ביצה", category: "חלבונים", calories: 155, protein: 13, carbs: 1.1, fat: 11, fiber: 0, servingSize: 50, servingDescription: "יחידה אחת" },
  { id: 3, name: "סטייק בקר", category: "חלבונים", calories: 271, protein: 26, carbs: 0, fat: 18, fiber: 0, servingSize: 200, servingDescription: "סטייק אחד" },
  { id: 4, name: "סלמון", category: "חלבונים", calories: 208, protein: 20, carbs: 0, fat: 13, fiber: 0, servingSize: 150, servingDescription: "פילה אחד" },
  { id: 5, name: "טונה (קופסה)", category: "חלבונים", calories: 116, protein: 26, carbs: 0, fat: 1, fiber: 0, servingSize: 100, servingDescription: "קופסה אחת" },
  { id: 6, name: "שניצל עוף", category: "חלבונים", calories: 297, protein: 18, carbs: 15, fat: 18, fiber: 0.5, servingSize: 150, servingDescription: "מנה אחת" },
  { id: 7, name: "קבב", category: "חלבונים", calories: 263, protein: 17, carbs: 3, fat: 20, fiber: 0.3, servingSize: 100, servingDescription: "שיפוד אחד" },
  { id: 8, name: "שווארמה", category: "חלבונים", calories: 215, protein: 19, carbs: 2, fat: 15, fiber: 0, servingSize: 150, servingDescription: "מנה אחת" },
  { id: 9, name: "המבורגר (קציצה)", category: "חלבונים", calories: 254, protein: 17, carbs: 0, fat: 20, fiber: 0, servingSize: 113, servingDescription: "קציצה אחת" },
  { id: 10, name: "חזה הודו", category: "חלבונים", calories: 135, protein: 30, carbs: 0, fat: 1, fiber: 0, servingSize: 150, servingDescription: "חזה אחד" },
  { id: 11, name: "נקניקייה", category: "חלבונים", calories: 301, protein: 11, carbs: 2, fat: 28, fiber: 0, servingSize: 50, servingDescription: "יחידה אחת" },
  { id: 12, name: "טופו", category: "חלבונים", calories: 76, protein: 8, carbs: 1.9, fat: 4.8, fiber: 0.3, servingSize: 120, servingDescription: "קוביה" },
  { id: 13, name: "שוק עוף", category: "חלבונים", calories: 209, protein: 20, carbs: 0, fat: 14, fiber: 0, servingSize: 130, servingDescription: "שוק אחת" },
  { id: 14, name: "כבד עוף", category: "חלבונים", calories: 167, protein: 24, carbs: 1, fat: 7, fiber: 0, servingSize: 100, servingDescription: "מנה אחת" },
  { id: 15, name: "דג אמנון (טילאפיה)", category: "חלבונים", calories: 96, protein: 20, carbs: 0, fat: 1.7, fiber: 0, servingSize: 150, servingDescription: "פילה אחד" },
  { id: 16, name: "דג בורי", category: "חלבונים", calories: 117, protein: 19, carbs: 0, fat: 4, fiber: 0, servingSize: 150, servingDescription: "פילה אחד" },
  { id: 17, name: "חזה עוף מעושן", category: "חלבונים", calories: 104, protein: 18, carbs: 2, fat: 2.5, fiber: 0, servingSize: 30, servingDescription: "פרוסה" },

  // ===== מוצרי חלב (Dairy) =====
  { id: 18, name: "קוטג' 5%", category: "מוצרי חלב", calories: 98, protein: 11, carbs: 3.5, fat: 5, fiber: 0, servingSize: 100, servingDescription: "גביע" },
  { id: 19, name: "קוטג' 0%", category: "מוצרי חלב", calories: 62, protein: 11, carbs: 3.5, fat: 0.4, fiber: 0, servingSize: 100, servingDescription: "גביע" },
  { id: 20, name: "יוגורט יווני", category: "מוצרי חלב", calories: 97, protein: 9, carbs: 3.6, fat: 5, fiber: 0, servingSize: 150, servingDescription: "גביע" },
  { id: 21, name: "חלב 3%", category: "מוצרי חלב", calories: 60, protein: 3.2, carbs: 4.7, fat: 3, fiber: 0, servingSize: 200, servingDescription: "כוס" },
  { id: 22, name: "גבינה צהובה", category: "מוצרי חלב", calories: 350, protein: 25, carbs: 1.3, fat: 27, fiber: 0, servingSize: 28, servingDescription: "פרוסה" },
  { id: 23, name: "גבינה לבנה 5%", category: "מוצרי חלב", calories: 84, protein: 12, carbs: 4, fat: 5, fiber: 0, servingSize: 100, servingDescription: "גביע" },
  { id: 24, name: "לאבנה", category: "מוצרי חלב", calories: 160, protein: 6, carbs: 5, fat: 13, fiber: 0, servingSize: 30, servingDescription: "כף" },
  { id: 25, name: "שמנת חמוצה", category: "מוצרי חלב", calories: 193, protein: 2.4, carbs: 4.6, fat: 19, fiber: 0, servingSize: 30, servingDescription: "כף" },
  { id: 26, name: "מוצרלה", category: "מוצרי חלב", calories: 280, protein: 22, carbs: 2.2, fat: 17, fiber: 0, servingSize: 30, servingDescription: "פרוסה" },
  { id: 27, name: "גבינת עיזים", category: "מוצרי חלב", calories: 364, protein: 22, carbs: 0.1, fat: 30, fiber: 0, servingSize: 30, servingDescription: "פרוסה" },
  { id: 28, name: "חלב 1%", category: "מוצרי חלב", calories: 42, protein: 3.4, carbs: 5, fat: 1, fiber: 0, servingSize: 200, servingDescription: "כוס" },
  { id: 29, name: "יוגורט טבעי", category: "מוצרי חלב", calories: 61, protein: 3.5, carbs: 4.7, fat: 3.3, fiber: 0, servingSize: 150, servingDescription: "גביע" },
  { id: 30, name: "גבינת פטה", category: "מוצרי חלב", calories: 264, protein: 14, carbs: 4, fat: 21, fiber: 0, servingSize: 30, servingDescription: "פרוסה" },
  { id: 31, name: "גבינת שמנת", category: "מוצרי חלב", calories: 342, protein: 6, carbs: 4, fat: 34, fiber: 0, servingSize: 30, servingDescription: "כף" },
  { id: 32, name: "יוגורט פירות", category: "מוצרי חלב", calories: 93, protein: 3.5, carbs: 15, fat: 1.5, fiber: 0.2, servingSize: 150, servingDescription: "גביע" },

  // ===== פחמימות (Carbs) =====
  { id: 33, name: "אורז לבן (מבושל)", category: "פחמימות", calories: 130, protein: 2.7, carbs: 28, fat: 0.3, fiber: 0.4, servingSize: 150, servingDescription: "כוס" },
  { id: 34, name: "אורז מלא (מבושל)", category: "פחמימות", calories: 123, protein: 2.7, carbs: 26, fat: 1, fiber: 1.8, servingSize: 150, servingDescription: "כוס" },
  { id: 35, name: "לחם לבן", category: "פחמימות", calories: 265, protein: 9, carbs: 49, fat: 3.2, fiber: 2.7, servingSize: 30, servingDescription: "פרוסה" },
  { id: 36, name: "לחם מלא", category: "פחמימות", calories: 247, protein: 13, carbs: 41, fat: 3.4, fiber: 7, servingSize: 30, servingDescription: "פרוסה" },
  { id: 37, name: "פיתה", category: "פחמימות", calories: 275, protein: 9, carbs: 56, fat: 1.2, fiber: 2.2, servingSize: 60, servingDescription: "יחידה אחת" },
  { id: 38, name: "פסטה (מבושלת)", category: "פחמימות", calories: 131, protein: 5, carbs: 25, fat: 1.1, fiber: 1.8, servingSize: 180, servingDescription: "צלחת" },
  { id: 39, name: "תפוח אדמה", category: "פחמימות", calories: 77, protein: 2, carbs: 17, fat: 0.1, fiber: 2.2, servingSize: 150, servingDescription: "יחידה בינונית" },
  { id: 40, name: "בטטה", category: "פחמימות", calories: 86, protein: 1.6, carbs: 20, fat: 0.1, fiber: 3, servingSize: 150, servingDescription: "יחידה בינונית" },
  { id: 41, name: "קוסקוס (מבושל)", category: "פחמימות", calories: 112, protein: 3.8, carbs: 23, fat: 0.2, fiber: 1.4, servingSize: 150, servingDescription: "כוס" },
  { id: 42, name: "בורגול (מבושל)", category: "פחמימות", calories: 83, protein: 3.1, carbs: 19, fat: 0.2, fiber: 4.5, servingSize: 150, servingDescription: "כוס" },
  { id: 43, name: "קינואה (מבושלת)", category: "פחמימות", calories: 120, protein: 4.4, carbs: 21, fat: 1.9, fiber: 2.8, servingSize: 150, servingDescription: "כוס" },
  { id: 44, name: "שיבולת שועל", category: "פחמימות", calories: 389, protein: 17, carbs: 66, fat: 7, fiber: 11, servingSize: 40, servingDescription: "חצי כוס" },
  { id: 45, name: "לחם שיפון", category: "פחמימות", calories: 259, protein: 9, carbs: 48, fat: 3.3, fiber: 5.8, servingSize: 30, servingDescription: "פרוסה" },
  { id: 46, name: "פסטה מלאה (מבושלת)", category: "פחמימות", calories: 124, protein: 5.3, carbs: 25, fat: 0.5, fiber: 3.9, servingSize: 180, servingDescription: "צלחת" },
  { id: 47, name: "תירס", category: "פחמימות", calories: 96, protein: 3.4, carbs: 21, fat: 1.5, fiber: 2.4, servingSize: 150, servingDescription: "קלח אחד" },
  { id: 48, name: "לחמנייה", category: "פחמימות", calories: 280, protein: 10, carbs: 50, fat: 4, fiber: 2, servingSize: 50, servingDescription: "יחידה אחת" },
  { id: 49, name: "קורנפלקס", category: "פחמימות", calories: 357, protein: 7, carbs: 84, fat: 0.4, fiber: 1.2, servingSize: 30, servingDescription: "כוס" },

  // ===== ירקות (Vegetables) =====
  { id: 50, name: "עגבנייה", category: "ירקות", calories: 18, protein: 0.9, carbs: 3.9, fat: 0.2, fiber: 1.2, servingSize: 120, servingDescription: "יחידה בינונית" },
  { id: 51, name: "מלפפון", category: "ירקות", calories: 15, protein: 0.7, carbs: 3.6, fat: 0.1, fiber: 0.5, servingSize: 100, servingDescription: "יחידה אחת" },
  { id: 52, name: "חסה", category: "ירקות", calories: 15, protein: 1.4, carbs: 2.9, fat: 0.2, fiber: 1.3, servingSize: 50, servingDescription: "כוס" },
  { id: 53, name: "ברוקולי", category: "ירקות", calories: 34, protein: 2.8, carbs: 7, fat: 0.4, fiber: 2.6, servingSize: 100, servingDescription: "כוס" },
  { id: 54, name: "גזר", category: "ירקות", calories: 41, protein: 0.9, carbs: 10, fat: 0.2, fiber: 2.8, servingSize: 70, servingDescription: "יחידה בינונית" },
  { id: 55, name: "פלפל אדום", category: "ירקות", calories: 31, protein: 1, carbs: 6, fat: 0.3, fiber: 2.1, servingSize: 120, servingDescription: "יחידה אחת" },
  { id: 56, name: "בצל", category: "ירקות", calories: 40, protein: 1.1, carbs: 9, fat: 0.1, fiber: 1.7, servingSize: 110, servingDescription: "יחידה בינונית" },
  { id: 57, name: "שום", category: "ירקות", calories: 149, protein: 6.4, carbs: 33, fat: 0.5, fiber: 2.1, servingSize: 3, servingDescription: "שן אחת" },
  { id: 58, name: "חציל", category: "ירקות", calories: 25, protein: 1, carbs: 6, fat: 0.2, fiber: 3, servingSize: 150, servingDescription: "יחידה בינונית" },
  { id: 59, name: "קישוא", category: "ירקות", calories: 17, protein: 1.2, carbs: 3.1, fat: 0.3, fiber: 1, servingSize: 120, servingDescription: "יחידה בינונית" },
  { id: 60, name: "כרובית", category: "ירקות", calories: 25, protein: 1.9, carbs: 5, fat: 0.3, fiber: 2, servingSize: 100, servingDescription: "כוס" },
  { id: 61, name: "תרד", category: "ירקות", calories: 23, protein: 2.9, carbs: 3.6, fat: 0.4, fiber: 2.2, servingSize: 30, servingDescription: "כוס" },
  { id: 62, name: "סלרי", category: "ירקות", calories: 16, protein: 0.7, carbs: 3, fat: 0.2, fiber: 1.6, servingSize: 40, servingDescription: "גבעול אחד" },
  { id: 63, name: "פטריות", category: "ירקות", calories: 22, protein: 3.1, carbs: 3.3, fat: 0.3, fiber: 1, servingSize: 100, servingDescription: "כוס" },
  { id: 64, name: "אבוקדו", category: "ירקות", calories: 160, protein: 2, carbs: 9, fat: 15, fiber: 7, servingSize: 80, servingDescription: "חצי יחידה" },
  { id: 65, name: "פלפל ירוק", category: "ירקות", calories: 20, protein: 0.9, carbs: 4.6, fat: 0.2, fiber: 1.7, servingSize: 120, servingDescription: "יחידה אחת" },
  { id: 66, name: "כרוב", category: "ירקות", calories: 25, protein: 1.3, carbs: 6, fat: 0.1, fiber: 2.5, servingSize: 80, servingDescription: "כוס" },
  { id: 67, name: "צנונית", category: "ירקות", calories: 16, protein: 0.7, carbs: 3.4, fat: 0.1, fiber: 1.6, servingSize: 15, servingDescription: "יחידה אחת" },
  { id: 68, name: "סלק", category: "ירקות", calories: 43, protein: 1.6, carbs: 10, fat: 0.2, fiber: 2.8, servingSize: 100, servingDescription: "יחידה בינונית" },
  { id: 69, name: "שעועית ירוקה", category: "ירקות", calories: 31, protein: 1.8, carbs: 7, fat: 0.1, fiber: 3.4, servingSize: 100, servingDescription: "כוס" },
  { id: 70, name: "אספרגוס", category: "ירקות", calories: 20, protein: 2.2, carbs: 3.9, fat: 0.1, fiber: 2.1, servingSize: 100, servingDescription: "5 יחידות" },
  { id: 71, name: "כרשינה (רוקט)", category: "ירקות", calories: 25, protein: 2.6, carbs: 3.7, fat: 0.7, fiber: 1.6, servingSize: 30, servingDescription: "כוס" },

  // ===== פירות (Fruits) =====
  { id: 72, name: "תפוח", category: "פירות", calories: 52, protein: 0.3, carbs: 14, fat: 0.2, fiber: 2.4, servingSize: 180, servingDescription: "יחידה בינונית" },
  { id: 73, name: "בננה", category: "פירות", calories: 89, protein: 1.1, carbs: 23, fat: 0.3, fiber: 2.6, servingSize: 120, servingDescription: "יחידה בינונית" },
  { id: 74, name: "תפוז", category: "פירות", calories: 47, protein: 0.9, carbs: 12, fat: 0.1, fiber: 2.4, servingSize: 150, servingDescription: "יחידה בינונית" },
  { id: 75, name: "אשכולית", category: "פירות", calories: 42, protein: 0.8, carbs: 11, fat: 0.1, fiber: 1.6, servingSize: 200, servingDescription: "חצי יחידה" },
  { id: 76, name: "ענבים", category: "פירות", calories: 69, protein: 0.7, carbs: 18, fat: 0.2, fiber: 0.9, servingSize: 150, servingDescription: "כוס" },
  { id: 77, name: "אבטיח", category: "פירות", calories: 30, protein: 0.6, carbs: 8, fat: 0.2, fiber: 0.4, servingSize: 200, servingDescription: "פרוסה" },
  { id: 78, name: "מלון", category: "פירות", calories: 34, protein: 0.8, carbs: 8, fat: 0.2, fiber: 0.9, servingSize: 200, servingDescription: "פרוסה" },
  { id: 79, name: "תות", category: "פירות", calories: 32, protein: 0.7, carbs: 8, fat: 0.3, fiber: 2, servingSize: 150, servingDescription: "כוס" },
  { id: 80, name: "אגס", category: "פירות", calories: 57, protein: 0.4, carbs: 15, fat: 0.1, fiber: 3.1, servingSize: 180, servingDescription: "יחידה בינונית" },
  { id: 81, name: "מנגו", category: "פירות", calories: 60, protein: 0.8, carbs: 15, fat: 0.4, fiber: 1.6, servingSize: 200, servingDescription: "יחידה בינונית" },
  { id: 82, name: "אננס", category: "פירות", calories: 50, protein: 0.5, carbs: 13, fat: 0.1, fiber: 1.4, servingSize: 150, servingDescription: "כוס" },
  { id: 83, name: "קיווי", category: "פירות", calories: 61, protein: 1.1, carbs: 15, fat: 0.5, fiber: 3, servingSize: 75, servingDescription: "יחידה אחת" },
  { id: 84, name: "תמר (מג'הול)", category: "פירות", calories: 277, protein: 1.8, carbs: 75, fat: 0.2, fiber: 6.7, servingSize: 24, servingDescription: "יחידה אחת" },
  { id: 85, name: "רימון", category: "פירות", calories: 83, protein: 1.7, carbs: 19, fat: 1.2, fiber: 4, servingSize: 150, servingDescription: "חצי יחידה" },
  { id: 86, name: "קלמנטינה", category: "פירות", calories: 47, protein: 0.9, carbs: 12, fat: 0.2, fiber: 1.7, servingSize: 75, servingDescription: "יחידה אחת" },
  { id: 87, name: "אפרסק", category: "פירות", calories: 39, protein: 0.9, carbs: 10, fat: 0.3, fiber: 1.5, servingSize: 150, servingDescription: "יחידה בינונית" },
  { id: 88, name: "שזיף", category: "פירות", calories: 46, protein: 0.7, carbs: 11, fat: 0.3, fiber: 1.4, servingSize: 66, servingDescription: "יחידה אחת" },
  { id: 89, name: "לימון", category: "פירות", calories: 29, protein: 1.1, carbs: 9, fat: 0.3, fiber: 2.8, servingSize: 60, servingDescription: "יחידה אחת" },

  // ===== מאכלים מוכנים (Prepared Foods) =====
  { id: 90, name: "חומוס", category: "מאכלים מוכנים", calories: 166, protein: 8, carbs: 14, fat: 10, fiber: 4, servingSize: 100, servingDescription: "מנה" },
  { id: 91, name: "טחינה", category: "מאכלים מוכנים", calories: 160, protein: 5, carbs: 8, fat: 12, fiber: 1.5, servingSize: 30, servingDescription: "כף" },
  { id: 92, name: "פלאפל", category: "מאכלים מוכנים", calories: 333, protein: 13, carbs: 32, fat: 18, fiber: 5, servingSize: 17, servingDescription: "כדור אחד" },
  { id: 93, name: "שקשוקה", category: "מאכלים מוכנים", calories: 95, protein: 6, carbs: 6, fat: 5.5, fiber: 1.2, servingSize: 200, servingDescription: "מנה" },
  { id: 94, name: "סלט ישראלי", category: "מאכלים מוכנים", calories: 50, protein: 1, carbs: 5, fat: 3, fiber: 1.5, servingSize: 150, servingDescription: "מנה" },
  { id: 95, name: "מרק עוף", category: "מאכלים מוכנים", calories: 36, protein: 3.5, carbs: 3, fat: 1.2, fiber: 0.4, servingSize: 250, servingDescription: "צלחת" },
  { id: 96, name: "מרק ירקות", category: "מאכלים מוכנים", calories: 30, protein: 1, carbs: 5, fat: 0.7, fiber: 1.5, servingSize: 250, servingDescription: "צלחת" },
  { id: 97, name: "ג'חנון", category: "מאכלים מוכנים", calories: 380, protein: 6, carbs: 42, fat: 22, fiber: 1.5, servingSize: 150, servingDescription: "יחידה אחת" },
  { id: 98, name: "מלוואח", category: "מאכלים מוכנים", calories: 340, protein: 6, carbs: 38, fat: 18, fiber: 1.2, servingSize: 120, servingDescription: "יחידה אחת" },
  { id: 99, name: "בורקס גבינה", category: "מאכלים מוכנים", calories: 310, protein: 8, carbs: 30, fat: 18, fiber: 1, servingSize: 100, servingDescription: "יחידה אחת" },
  { id: 100, name: "בורקס תפוח אדמה", category: "מאכלים מוכנים", calories: 290, protein: 5, carbs: 35, fat: 15, fiber: 1.5, servingSize: 100, servingDescription: "יחידה אחת" },
  { id: 101, name: "סמבוסק", category: "מאכלים מוכנים", calories: 320, protein: 7, carbs: 28, fat: 20, fiber: 1, servingSize: 60, servingDescription: "יחידה אחת" },
  { id: 102, name: "לחוח", category: "מאכלים מוכנים", calories: 210, protein: 6, carbs: 38, fat: 3.5, fiber: 1.8, servingSize: 100, servingDescription: "יחידה אחת" },
  { id: 103, name: "מג'דרה", category: "מאכלים מוכנים", calories: 140, protein: 6, carbs: 23, fat: 3, fiber: 3.5, servingSize: 200, servingDescription: "מנה" },
  { id: 104, name: "חציל בתנור", category: "מאכלים מוכנים", calories: 75, protein: 1.5, carbs: 8, fat: 4, fiber: 3, servingSize: 150, servingDescription: "מנה" },
  { id: 105, name: "פיצה (משולש)", category: "מאכלים מוכנים", calories: 266, protein: 11, carbs: 33, fat: 10, fiber: 2.3, servingSize: 107, servingDescription: "משולש אחד" },
  { id: 106, name: "סלט חצילים", category: "מאכלים מוכנים", calories: 120, protein: 1.5, carbs: 7, fat: 10, fiber: 2.5, servingSize: 100, servingDescription: "מנה" },
  { id: 107, name: "כרוביות בתנור", category: "מאכלים מוכנים", calories: 90, protein: 3, carbs: 10, fat: 4.5, fiber: 3, servingSize: 150, servingDescription: "מנה" },
  { id: 108, name: "מעפיל", category: "מאכלים מוכנים", calories: 230, protein: 9, carbs: 3, fat: 20, fiber: 0, servingSize: 100, servingDescription: "מנה" },
  { id: 109, name: "צ'יפס (אפוי)", category: "מאכלים מוכנים", calories: 160, protein: 2, carbs: 24, fat: 6, fiber: 2, servingSize: 150, servingDescription: "מנה" },
  { id: 110, name: "צ'יפס (מטוגן)", category: "מאכלים מוכנים", calories: 312, protein: 3.4, carbs: 41, fat: 15, fiber: 3.8, servingSize: 150, servingDescription: "מנה" },

  // ===== חטיפים ומתוקים (Snacks & Sweets) =====
  { id: 111, name: "במבה", category: "חטיפים ומתוקים", calories: 546, protein: 11, carbs: 52, fat: 33, fiber: 3, servingSize: 25, servingDescription: "שקית קטנה" },
  { id: 112, name: "ביסלי", category: "חטיפים ומתוקים", calories: 475, protein: 8, carbs: 63, fat: 21, fiber: 2.5, servingSize: 25, servingDescription: "שקית קטנה" },
  { id: 113, name: "שוקולד מריר", category: "חטיפים ומתוקים", calories: 546, protein: 5, carbs: 60, fat: 32, fiber: 7, servingSize: 25, servingDescription: "קוביה" },
  { id: 114, name: "שוקולד חלב", category: "חטיפים ומתוקים", calories: 535, protein: 7.6, carbs: 59, fat: 30, fiber: 1.5, servingSize: 25, servingDescription: "קוביה" },
  { id: 115, name: "עוגיות", category: "חטיפים ומתוקים", calories: 480, protein: 5, carbs: 64, fat: 23, fiber: 1.5, servingSize: 30, servingDescription: "יחידה אחת" },
  { id: 116, name: "קרקר", category: "חטיפים ומתוקים", calories: 430, protein: 9, carbs: 70, fat: 12, fiber: 2.5, servingSize: 15, servingDescription: "יחידה אחת" },
  { id: 117, name: "חטיף אנרגיה", category: "חטיפים ומתוקים", calories: 420, protein: 10, carbs: 55, fat: 18, fiber: 4, servingSize: 40, servingDescription: "חטיף אחד" },
  { id: 118, name: "גרנולה", category: "חטיפים ומתוקים", calories: 471, protein: 10, carbs: 64, fat: 20, fiber: 5, servingSize: 45, servingDescription: "חצי כוס" },
  { id: 119, name: "פופקורן", category: "חטיפים ומתוקים", calories: 387, protein: 13, carbs: 78, fat: 4.5, fiber: 15, servingSize: 30, servingDescription: "כוס" },
  { id: 120, name: "קרמבו", category: "חטיפים ומתוקים", calories: 400, protein: 4, carbs: 62, fat: 16, fiber: 1, servingSize: 28, servingDescription: "יחידה אחת" },
  { id: 121, name: "עוגת שוקולד", category: "חטיפים ומתוקים", calories: 371, protein: 5, carbs: 50, fat: 17, fiber: 2, servingSize: 80, servingDescription: "פרוסה" },
  { id: 122, name: "חלווה", category: "חטיפים ומתוקים", calories: 516, protein: 13, carbs: 50, fat: 30, fiber: 3, servingSize: 30, servingDescription: "פרוסה" },
  { id: 123, name: "גלידה וניל", category: "חטיפים ומתוקים", calories: 207, protein: 3.5, carbs: 24, fat: 11, fiber: 0, servingSize: 66, servingDescription: "כדור אחד" },

  // ===== שומנים ושמנים (Fats & Oils) =====
  { id: 124, name: "שמן זית", category: "שומנים ושמנים", calories: 884, protein: 0, carbs: 0, fat: 100, fiber: 0, servingSize: 14, servingDescription: "כף" },
  { id: 125, name: "חמאה", category: "שומנים ושמנים", calories: 717, protein: 0.9, carbs: 0.1, fat: 81, fiber: 0, servingSize: 14, servingDescription: "כף" },
  { id: 126, name: "חמאת בוטנים", category: "שומנים ושמנים", calories: 588, protein: 25, carbs: 20, fat: 50, fiber: 6, servingSize: 32, servingDescription: "כף" },
  { id: 127, name: "טחינה גולמית", category: "שומנים ושמנים", calories: 595, protein: 17, carbs: 21, fat: 54, fiber: 9, servingSize: 15, servingDescription: "כף" },
  { id: 128, name: "אגוזי מלך", category: "שומנים ושמנים", calories: 654, protein: 15, carbs: 14, fat: 65, fiber: 6.7, servingSize: 28, servingDescription: "קומץ" },
  { id: 129, name: "שקדים", category: "שומנים ושמנים", calories: 579, protein: 21, carbs: 22, fat: 50, fiber: 12, servingSize: 28, servingDescription: "קומץ" },
  { id: 130, name: "בוטנים", category: "שומנים ושמנים", calories: 567, protein: 26, carbs: 16, fat: 49, fiber: 8.5, servingSize: 28, servingDescription: "קומץ" },
  { id: 131, name: "קשיו", category: "שומנים ושמנים", calories: 553, protein: 18, carbs: 30, fat: 44, fiber: 3.3, servingSize: 28, servingDescription: "קומץ" },
  { id: 132, name: "אגוזי פקאן", category: "שומנים ושמנים", calories: 691, protein: 9, carbs: 14, fat: 72, fiber: 9.6, servingSize: 28, servingDescription: "קומץ" },
  { id: 133, name: "שמן קנולה", category: "שומנים ושמנים", calories: 884, protein: 0, carbs: 0, fat: 100, fiber: 0, servingSize: 14, servingDescription: "כף" },
  { id: 134, name: "זיתים", category: "שומנים ושמנים", calories: 115, protein: 0.8, carbs: 6, fat: 11, fiber: 3.2, servingSize: 30, servingDescription: "5 יחידות" },
  { id: 135, name: "גרעיני חמנייה", category: "שומנים ושמנים", calories: 584, protein: 21, carbs: 20, fat: 51, fiber: 9, servingSize: 28, servingDescription: "קומץ" },
  { id: 136, name: "חמאת שקדים", category: "שומנים ושמנים", calories: 614, protein: 21, carbs: 19, fat: 56, fiber: 10, servingSize: 32, servingDescription: "כף" },

  // ===== קטניות ודגנים (Legumes & Grains) =====
  { id: 137, name: "עדשים (מבושלות)", category: "קטניות ודגנים", calories: 116, protein: 9, carbs: 20, fat: 0.4, fiber: 8, servingSize: 180, servingDescription: "כוס" },
  { id: 138, name: "חומוס גרגירים (מבושל)", category: "קטניות ודגנים", calories: 164, protein: 9, carbs: 27, fat: 2.6, fiber: 8, servingSize: 180, servingDescription: "כוס" },
  { id: 139, name: "שעועית לבנה (מבושלת)", category: "קטניות ודגנים", calories: 139, protein: 10, carbs: 25, fat: 0.5, fiber: 6, servingSize: 180, servingDescription: "כוס" },
  { id: 140, name: "אדממה", category: "קטניות ודגנים", calories: 121, protein: 12, carbs: 9, fat: 5, fiber: 5, servingSize: 100, servingDescription: "כוס" },
  { id: 141, name: "חומוס מבושל", category: "קטניות ודגנים", calories: 164, protein: 9, carbs: 27, fat: 2.6, fiber: 8, servingSize: 180, servingDescription: "כוס" },
  { id: 142, name: "שעועית אדומה (מבושלת)", category: "קטניות ודגנים", calories: 127, protein: 9, carbs: 22, fat: 0.5, fiber: 6.4, servingSize: 180, servingDescription: "כוס" },
  { id: 143, name: "אורז בסמטי (מבושל)", category: "קטניות ודגנים", calories: 121, protein: 3.5, carbs: 25, fat: 0.4, fiber: 0.4, servingSize: 150, servingDescription: "כוס" },
  { id: 144, name: "פול מצרי (מבושל)", category: "קטניות ודגנים", calories: 110, protein: 8, carbs: 19, fat: 0.4, fiber: 5, servingSize: 180, servingDescription: "כוס" },
  { id: 145, name: "עדשים אדומות (מבושלות)", category: "קטניות ודגנים", calories: 116, protein: 9, carbs: 20, fat: 0.4, fiber: 4, servingSize: 180, servingDescription: "כוס" },

  // ===== משקאות (Beverages) =====
  { id: 146, name: "קפה שחור", category: "משקאות", calories: 2, protein: 0.3, carbs: 0, fat: 0, fiber: 0, servingSize: 240, servingDescription: "כוס" },
  { id: 147, name: "קפה עם חלב", category: "משקאות", calories: 30, protein: 1.5, carbs: 3, fat: 1.2, fiber: 0, servingSize: 240, servingDescription: "כוס" },
  { id: 148, name: "מיץ תפוזים", category: "משקאות", calories: 45, protein: 0.7, carbs: 10, fat: 0.2, fiber: 0.2, servingSize: 250, servingDescription: "כוס" },
  { id: 149, name: "קולה", category: "משקאות", calories: 42, protein: 0, carbs: 11, fat: 0, fiber: 0, servingSize: 330, servingDescription: "פחית" },
  { id: 150, name: "בירה", category: "משקאות", calories: 43, protein: 0.5, carbs: 3.6, fat: 0, fiber: 0, servingSize: 330, servingDescription: "בקבוק" },
  { id: 151, name: "יין אדום", category: "משקאות", calories: 85, protein: 0.1, carbs: 2.6, fat: 0, fiber: 0, servingSize: 150, servingDescription: "כוס" },
  { id: 152, name: "חלב שקדים", category: "משקאות", calories: 17, protein: 0.6, carbs: 1.4, fat: 1.1, fiber: 0.2, servingSize: 240, servingDescription: "כוס" },
  { id: 153, name: "חלב סויה", category: "משקאות", calories: 33, protein: 2.8, carbs: 1.2, fat: 1.8, fiber: 0.4, servingSize: 240, servingDescription: "כוס" },
  { id: 154, name: "מיץ גזר", category: "משקאות", calories: 40, protein: 0.9, carbs: 9, fat: 0.2, fiber: 0.8, servingSize: 250, servingDescription: "כוס" },
  { id: 155, name: "סמוזי פירות", category: "משקאות", calories: 65, protein: 1, carbs: 15, fat: 0.3, fiber: 1.5, servingSize: 300, servingDescription: "כוס" },
  { id: 156, name: "תה ירוק", category: "משקאות", calories: 1, protein: 0, carbs: 0.2, fat: 0, fiber: 0, servingSize: 240, servingDescription: "כוס" },
  { id: 157, name: "קולה דיאט", category: "משקאות", calories: 0, protein: 0, carbs: 0, fat: 0, fiber: 0, servingSize: 330, servingDescription: "פחית" },
  { id: 158, name: "לימונדה", category: "משקאות", calories: 40, protein: 0, carbs: 10, fat: 0, fiber: 0, servingSize: 250, servingDescription: "כוס" },

  // ===== תוספות ורטבים (Common Additions) =====
  { id: 159, name: "סוכר", category: "חטיפים ומתוקים", calories: 387, protein: 0, carbs: 100, fat: 0, fiber: 0, servingSize: 5, servingDescription: "כפית" },
  { id: 160, name: "דבש", category: "חטיפים ומתוקים", calories: 304, protein: 0.3, carbs: 82, fat: 0, fiber: 0.2, servingSize: 21, servingDescription: "כף" },
  { id: 161, name: "ריבה", category: "חטיפים ומתוקים", calories: 250, protein: 0.4, carbs: 63, fat: 0.1, fiber: 1, servingSize: 20, servingDescription: "כף" },
  { id: 162, name: "ממרח שוקולד", category: "חטיפים ומתוקים", calories: 539, protein: 6, carbs: 58, fat: 31, fiber: 3, servingSize: 20, servingDescription: "כף" },
  { id: 163, name: "קטשופ", category: "מאכלים מוכנים", calories: 112, protein: 1.7, carbs: 26, fat: 0.1, fiber: 0.3, servingSize: 17, servingDescription: "כף" },
  { id: 164, name: "מיונז", category: "שומנים ושמנים", calories: 680, protein: 1, carbs: 0.6, fat: 75, fiber: 0, servingSize: 15, servingDescription: "כף" },
  { id: 165, name: "חרדל", category: "מאכלים מוכנים", calories: 66, protein: 4, carbs: 6, fat: 3, fiber: 3, servingSize: 5, servingDescription: "כפית" },
  { id: 166, name: "רוטב סויה", category: "מאכלים מוכנים", calories: 53, protein: 8, carbs: 5, fat: 0.1, fiber: 0.8, servingSize: 15, servingDescription: "כף" },
  { id: 167, name: "רוטב צ'ילי מתוק", category: "מאכלים מוכנים", calories: 220, protein: 0.5, carbs: 54, fat: 0.3, fiber: 0.5, servingSize: 15, servingDescription: "כף" },
  { id: 168, name: "מטבולה", category: "מאכלים מוכנים", calories: 157, protein: 2, carbs: 8, fat: 13, fiber: 2, servingSize: 100, servingDescription: "מנה" },
  { id: 169, name: "סחוג", category: "מאכלים מוכנים", calories: 70, protein: 2, carbs: 5, fat: 5, fiber: 2.5, servingSize: 10, servingDescription: "כפית" },
  { id: 170, name: "עמבה", category: "מאכלים מוכנים", calories: 50, protein: 0.5, carbs: 8, fat: 2, fiber: 1, servingSize: 15, servingDescription: "כף" }
];
